spring.application.name=employeemanager

spring.datasource.url=jdbc:postgresql://localhost:5432/employeedb
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=7f2e91c84b5d2a7e3c9f1d6a8b4e2f5c9d7a1b3e6f8c2d4a9b7e5f1c3d8a6b2


